server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        server-addr: http://47.113.207.103:1111/ #配置阿里云服务器 nginx 代理到nacos集群的地址

management:
  endpoints:
    web:
      exposure:
        include: '*'